spring:
  application:
    name: learn
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_hiber?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: user
    password: resu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
maxCar: 3
disabledFiltersList: Model,Color

loan-properties:
  min-car-cost-for-loan-approve: 1000000
  min-user-income-for-loan-approve: 40000
  max-approve-multiplier-of-car-cost: 0.30
  max-approve-multiplier-of-count-of-months-income: 6
  users-income-uri: https://66055cd12ca9478ea1801f2e.mockapi.io/api/users/income


